import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCards from '../components/LargeCards'
import MediumCards from '../components/MediumCards'
import SmallCards from '../components/SmallCards'
import styles from '../styles/Home.module.css'

export default function Home({data, dataCards}) {
  return (
    <div >
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <Header />
      <Banner />

      <main className=' max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
            <h2 className=' text-4xl font-semibold pb-5'>Explore Nearby</h2>

           {/*server - API endPoints */}

        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
      {
        data?.map(element => (
          
             <SmallCards key={element.img} 
                         img={element.img}
                         distance={element.distance}
                         location={element.location}
              />
        ))
      }
      </div>
        </section>

        {/* CardsMD */}

        <section>
        <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>

      <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
      {
          dataCards?.map(element => (
              <MediumCards key={element.img} 
                           img={element.img}
                           title={element.title} 
                           />
          )) }

      </div>

      </section>

      <LargeCards 
                  img='https://links.papareact.com/4cj' 
                  title='The Greatest Outdoors'
                  description='Wishlist curated by Airbnb'
                  buttonText='Get Inspired'
                  />

      </main>

      <Footer />

    </div>
  )
}


export async function getStaticProps(){
  const res = await fetch('https://www.jsonkeeper.com/b/4G1G');
  const data = await res.json();

  const resCards = await fetch('https://www.jsonkeeper.com/b/VHHT');
  const dataCards = await resCards.json()


  return  {
    props: {
      data,
      dataCards,
    }
  }

}